### ISSUE TITLE
ImportError: cannot import name 'pad_sequences'

### ISSUE THREAD

**Issue by SeekPoint** [zhaoluffy/BiLSTM-CRF#1]
mldl@mldlUB1604:~/ub16_prj/BiLSTM-CRF$ python3 train.py 
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from src.data.data_manager import DataManager
  File "/home/mldl/ub16_prj/BiLSTM-CRF/src/data/data_manager.py", line 2, in <module>
    from src.utils.data_utils import pad_sequences, iob_iobes, iob2
ImportError: cannot import name 'pad_sequences'
mldl@mldlUB1604:~/ub16_prj/BiLSTM-CRF$

**Comment by zhaoluffy** [comment]
May need add current path into your python path

**Comment by SeekPoint** [comment]
PYTHONPATH=. python3 train.py
still got this error

**Comment by zhaoluffy** [comment]
try using sys.path.append("your project root path")
